//---------------------------------------------------------------------------

#ifndef guimainH
#define guimainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ToolWin.hpp>
#include <ExtCtrls.hpp>
#include "LMDButton.hpp"
#include "LMDCustomButton.hpp"
#include <Menus.hpp>
#include <Dialogs.hpp>

#include "Settings.h"
#include "../Mediator.h"
#include "../Song/SongFacade.h"
#include "../ImportExport/ImportExportFacade.h"
#include "../Database/DatabaseEngine.h"
//#include "../Playlist/PlaylistFacade.h"
#include "../Player/PlayerFacade.h"
#include "LMDCustomComponent.hpp"
#include "LMDTrayIcon.hpp"
#include "LMDWndProcComponent.hpp"
//---------------------------------------------------------------------------
class SongProperty;

class TMainForm : public TForm
{
__published:	// IDE-managed Components
    TStatusBar *StatusBar;
    TPanel *Panel1;
    TPanel *Panel2;
    TListView *SongList;
    TPopupMenu *GenrePopupMenu;
    TLMDButton *LMDButton1;
    TMenuItem *Rock1;
    TLMDButton *LMDButton2;
    TLMDButton *LMDButton3;
    TMenuItem *Dance2;
    TMenuItem *Hiphop1;
    TMenuItem *Reggae1;
    TMenuItem *Country1;
    TMenuItem *Electronica1;
    TMenuItem *NewAge2;
    TMenuItem *Vokal1;
    TMenuItem *Gospel1;
    TMenuItem *Lttlyssnat1;
    TMenuItem *Folkmusik1;
    TMenuItem *Soundtrack1;
    TMenuItem *Vrldsmusik1;
    TMenuItem *AvantGarde1;
    TMenuItem *vrigt1;
    TMenuItem *AlternativeRock1;
    TMenuItem *NewWave1;
    TMenuItem *Punk1;
    TMenuItem *Hrdrock1;
    TMenuItem *RocknRoll1;
    TMenuItem *PsykedeliskRock1;
    TMenuItem *ProgressivRock1;
    TMenuItem *Pop1;
    TMenuItem *CountryRock1;
    TMenuItem *SlowRock1;
    TMenuItem *SoftRock1;
    TMenuItem *Merseybeat1;
    TMenuItem *Rock2;
    TMenuItem *N1;
    TMenuItem *Europop1;
    TMenuItem *Topp401;
    TMenuItem *Japanskpop1;
    TMenuItem *N2;
    TMenuItem *Pop2;
    TMenuItem *SouthernRock1;
    TMenuItem *Metal1;
    TMenuItem *Hrdrock2;
    TMenuItem *N3;
    TMenuItem *HeavyMetal1;
    TMenuItem *BlackMetal1;
    TMenuItem *DeathMetal1;
    TMenuItem *ThrashMetal1;
    TMenuItem *Primus1;
    TMenuItem *Metal2;
    TMenuItem *N4;
    TMenuItem *Instrumentalrock1;
    TMenuItem *RockRoll1;
    TMenuItem *N5;
    TMenuItem *Rockabilly1;
    TMenuItem *Indierock1;
    TMenuItem *AlternativeRock2;
    TMenuItem *N6;
    TMenuItem *DreamPop1;
    TMenuItem *BritPop1;
    TMenuItem *GothicRock1;
    TMenuItem *Grunge1;
    TMenuItem *CollegeRock1;
    TMenuItem *LoFi1;
    TMenuItem *Punk2;
    TMenuItem *N7;
    TMenuItem *AcidPunk1;
    TMenuItem *Negerpunk1;
    TMenuItem *PolskPunk1;
    TMenuItem *ProgressivRock2;
    TMenuItem *N8;
    TMenuItem *Symfoniskrock1;
    TMenuItem *Psykedeliskrock2;
    TMenuItem *N9;
    TMenuItem *GarageRock1;
    TMenuItem *Blues1;
    TMenuItem *N10;
    TMenuItem *BluesRock1;
    TMenuItem *ChicagoBlues1;
    TMenuItem *CountryBlues1;
    TMenuItem *PianoBlues1;
    TMenuItem *TexasBlues1;
    TMenuItem *RB1;
    TMenuItem *N11;
    TMenuItem *DooWop1;
    TMenuItem *Funk1;
    TMenuItem *QuietStorm1;
    TMenuItem *Urban1;
    TMenuItem *Soul2;
    TMenuItem *Funk2;
    TMenuItem *N12;
    TMenuItem *PopFunk1;
    TMenuItem *Soul3;
    TMenuItem *N13;
    TMenuItem *Motown1;
    TMenuItem *RhythmicSoul1;
    TMenuItem *Jazz1;
    TMenuItem *N14;
    TMenuItem *Bebop1;
    TMenuItem *Fusion1;
    TMenuItem *JazzFunk1;
    TMenuItem *NewOrleans1;
    TMenuItem *SoulJazz1;
    TMenuItem *Swing1;
    TMenuItem *Fusion2;
    TMenuItem *N15;
    TMenuItem *FastFusion1;
    TMenuItem *Klassiskt1;
    TMenuItem *N16;
    TMenuItem *Kammarmusik1;
    TMenuItem *Opera1;
    TMenuItem *Sonat1;
    TMenuItem *Symfoni1;
    TMenuItem *Medeltida1;
    TMenuItem *Barock1;
    TMenuItem *Romantisk1;
    TMenuItem *Renssans1;
    TMenuItem *Impressionist1;
    TMenuItem *Expressionist1;
    TMenuItem *Dance3;
    TMenuItem *N17;
    TMenuItem *Freestyle1;
    TMenuItem *Eurodance1;
    TMenuItem *Club1;
    TMenuItem *Disco1;
    TMenuItem *Club2;
    TMenuItem *N18;
    TMenuItem *ClubHouse1;
    TMenuItem *Rap1;
    TMenuItem *BassMusic1;
    TMenuItem *Hiphop2;
    TMenuItem *N19;
    TMenuItem *BassMusic2;
    TMenuItem *N20;
    TMenuItem *MiamiBass1;
    TMenuItem *Rap2;
    TMenuItem *N21;
    TMenuItem *GangstaRap1;
    TMenuItem *Reggae2;
    TMenuItem *N22;
    TMenuItem *Dancehall1;
    TMenuItem *Dub1;
    TMenuItem *Ska1;
    TMenuItem *Country2;
    TMenuItem *N23;
    TMenuItem *Bluegrass1;
    TMenuItem *CountryPop1;
    TMenuItem *Honkytonk1;
    TMenuItem *Electronica2;
    TMenuItem *N24;
    TMenuItem *Ambient1;
    TMenuItem *AcidJazz1;
    TMenuItem *Industrial1;
    TMenuItem *House1;
    TMenuItem *Techno1;
    TMenuItem *Breakbeat1;
    TMenuItem *TripHop1;
    TMenuItem *HardcoreTechno1;
    TMenuItem *Trance1;
    TMenuItem *Industrial2;
    TMenuItem *N25;
    TMenuItem *Darkwave1;
    TMenuItem *House2;
    TMenuItem *N26;
    TMenuItem *EuroHouse1;
    TMenuItem *AcidHouse1;
    TMenuItem *Techno2;
    TMenuItem *N27;
    TMenuItem *EuroTechno1;
    TMenuItem *TechnoIndustrial1;
    TMenuItem *DrumBass1;
    TMenuItem *DrumBass2;
    TMenuItem *N28;
    TMenuItem *Jungle1;
    TMenuItem *HardcoreTechno2;
    TMenuItem *N29;
    TMenuItem *Rave1;
    TMenuItem *Terrorcore1;
    TMenuItem *HappyHardcore1;
    TMenuItem *Trance2;
    TMenuItem *N30;
    TMenuItem *Goa1;
    TMenuItem *Avslappning1;
    TMenuItem *Neoklassisk1;
    TMenuItem *Natur1;
    TMenuItem *Meditativ1;
    TMenuItem *Space1;
    TMenuItem *Showtunes1;
    TMenuItem *Acappella1;
    TMenuItem *Kabar1;
    TMenuItem *Krsng1;
    TMenuItem *Ballad1;
    TMenuItem *Duett1;
    TMenuItem *Gregoriansksng1;
    TMenuItem *Vokalistgrupp1;
    TMenuItem *Barbershop1;
    TMenuItem *Gospel2;
    TMenuItem *N31;
    TMenuItem *BlackGospel1;
    TMenuItem *CCM1;
    TMenuItem *CCM2;
    TMenuItem *N32;
    TMenuItem *Kristenrock1;
    TMenuItem *Kristenrap1;
    TMenuItem *Kristengangstarap1;
    TMenuItem *Lovsng1;
    TMenuItem *Lttlyssnat2;
    TMenuItem *N33;
    TMenuItem *Hissmusik1;
    TMenuItem *Polka1;
    TMenuItem *Orkestral1;
    TMenuItem *MoodMusic1;
    TMenuItem *Instrumentalpop1;
    TMenuItem *Soundtrack2;
    TMenuItem *N34;
    TMenuItem *Filmmusik1;
    TMenuItem *TVmusik1;
    TMenuItem *Musikal1;
    TMenuItem *Dataspel1;
    TMenuItem *Anime1;
    TMenuItem *Filmmusik2;
    TMenuItem *N35;
    TMenuItem *Trailer1;
    TMenuItem *PornGroove1;
    TMenuItem *Folkmusik2;
    TMenuItem *N36;
    TMenuItem *FolkPop1;
    TMenuItem *FolkRock1;
    TMenuItem *NationalFolk1;
    TMenuItem *Amerikanskindian1;
    TMenuItem *Chanson1;
    TMenuItem *Folkvisa1;
    TMenuItem *Vrldsmusik2;
    TMenuItem *N37;
    TMenuItem *Etnisk1;
    TMenuItem *Afrikansk1;
    TMenuItem *Folklore1;
    TMenuItem *Keltisk1;
    TMenuItem *Latinsk1;
    TMenuItem *Latinsk2;
    TMenuItem *N38;
    TMenuItem *Bossanova1;
    TMenuItem *Merengue1;
    TMenuItem *Salsa1;
    TMenuItem *Samba1;
    TMenuItem *Tango1;
    TMenuItem *SoundArt1;
    TMenuItem *Improviseradmusik1;
    TMenuItem *AvantGarde2;
    TMenuItem *N39;
    TMenuItem *SoundArt2;
    TMenuItem *N40;
    TMenuItem *Noise1;
    TMenuItem *Tal1;
    TMenuItem *Ljudklipp1;
    TMenuItem *Humor1;
    TMenuItem *Crossover1;
    TMenuItem *SlowJam1;
    TMenuItem *Kult1;
    TMenuItem *Revival1;
    TMenuItem *Retro1;
    TMenuItem *Akustisk1;
    TMenuItem *Hardcore1;
    TMenuItem *Tribal1;
    TMenuItem *PowerBallad1;
    TMenuItem *Oldies1;
    TMenuItem *Alternative1;
    TMenuItem *Instrumental1;
    TMenuItem *Ljudklipp2;
    TMenuItem *N41;
    TMenuItem *Trumsolo1;
    TMenuItem *Humor2;
    TMenuItem *N42;
    TMenuItem *Spratt1;
    TMenuItem *Satir1;
    TPopupMenu *YearPopupMenu;
    TMenuItem *N2000talet1;
    TMenuItem *N1990talet1;
    TMenuItem *N1980talet1;
    TMenuItem *N1970talet1;
    TMenuItem *N1960talet1;
    TMenuItem *N1950talet1;
    TMenuItem *Hela1990talet1;
    TMenuItem *N43;
    TMenuItem *N19991;
    TMenuItem *N19981;
    TMenuItem *N19971;
    TMenuItem *N19961;
    TMenuItem *N19951;
    TMenuItem *N19941;
    TMenuItem *N19931;
    TMenuItem *N19921;
    TMenuItem *N19911;
    TMenuItem *N19901;
    TMenuItem *Hela1980talet1;
    TMenuItem *N44;
    TMenuItem *N19891;
    TMenuItem *N19881;
    TMenuItem *N19871;
    TMenuItem *N19861;
    TMenuItem *N19851;
    TMenuItem *N19841;
    TMenuItem *N19831;
    TMenuItem *N19821;
    TMenuItem *N19811;
    TMenuItem *N19801;
    TMenuItem *Hela1970talet1;
    TMenuItem *N45;
    TMenuItem *N19791;
    TMenuItem *N19781;
    TMenuItem *N19771;
    TMenuItem *N19761;
    TMenuItem *N19751;
    TMenuItem *N19741;
    TMenuItem *N19731;
    TMenuItem *N19721;
    TMenuItem *N19711;
    TMenuItem *N19701;
    TMenuItem *Hela2000talet1;
    TMenuItem *N46;
    TMenuItem *N20031;
    TMenuItem *N20021;
    TMenuItem *N20011;
    TMenuItem *N20001;
    TMenuItem *Hela1960talet1;
    TMenuItem *N47;
    TMenuItem *N19691;
    TMenuItem *N19681;
    TMenuItem *N19671;
    TMenuItem *N19661;
    TMenuItem *N19651;
    TMenuItem *N19641;
    TMenuItem *N19631;
    TMenuItem *N19621;
    TMenuItem *N19611;
    TMenuItem *N19601;
    TMenuItem *Hela1950talet1;
    TMenuItem *N48;
    TMenuItem *N19591;
    TMenuItem *N19581;
    TMenuItem *N19571;
    TMenuItem *N19561;
    TMenuItem *N19551;
    TMenuItem *N19541;
    TMenuItem *N19531;
    TMenuItem *N19521;
    TMenuItem *N19511;
    TMenuItem *N19501;
    TMenuItem *N20041;
    TPopupMenu *ArtistPopupMenu;
    TMenuItem *AD1;
    TMenuItem *EH1;
    TMenuItem *IL1;
    TMenuItem *MP1;
    TMenuItem *QT1;
    TMenuItem *UX1;
    TMenuItem *Y1;
    TMenuItem *AllaAD1;
    TMenuItem *N50;
    TMenuItem *A1;
    TMenuItem *B1;
    TMenuItem *C1;
    TMenuItem *D1;
    TMenuItem *AllaEH1;
    TMenuItem *N51;
    TMenuItem *E1;
    TMenuItem *F1;
    TMenuItem *G1;
    TMenuItem *H1;
    TMenuItem *AllaIL1;
    TMenuItem *N52;
    TMenuItem *I1;
    TMenuItem *J1;
    TMenuItem *K1;
    TMenuItem *L1;
    TMenuItem *AllaMP1;
    TMenuItem *N53;
    TMenuItem *M1;
    TMenuItem *N54;
    TMenuItem *O1;
    TMenuItem *P1;
    TMenuItem *AllaQT1;
    TMenuItem *N55;
    TMenuItem *Q1;
    TMenuItem *R1;
    TMenuItem *S1;
    TMenuItem *T1;
    TMenuItem *AllaUX1;
    TMenuItem *N56;
    TMenuItem *U1;
    TMenuItem *V1;
    TMenuItem *W1;
    TMenuItem *X1;
    TMenuItem *AllaY1;
    TMenuItem *N57;
    TMenuItem *Y2;
    TMenuItem *Z1;
    TMenuItem *N58;
    TMenuItem *N59;
    TMenuItem *N60;
    TLMDButton *LMDButton4;
    TLMDButton *LMDButton5;
    TLMDButton *LMDButton6;
    TPopupMenu *RatingPopupMenu;
    TMenuItem *Utmrkt1;
    TMenuItem *Mycketbra41;
    TMenuItem *Bra31;
    TMenuItem *OK21;
    TMenuItem *Dlig11;
    TPopupMenu *SituationPopupMenu;
    TMenuItem *Dans1;
    TMenuItem *Fest1;
    TMenuItem *Romantik1;
    TMenuItem *Middag1;
    TMenuItem *Bakgrund1;
    TMenuItem *Avkoppling1;
    TMenuItem *RB2;
    TMenuItem *Blues2;
    TMenuItem *Jazz2;
    TMenuItem *Klassiskt2;
    TPopupMenu *MoodPopupMenu;
    TMenuItem *Vild1;
    TMenuItem *Glad1;
    TMenuItem *Surmulen1;
    TMenuItem *Ltt1;
    TMenuItem *Stillsam1;
    TMenuItem *Dsig1;
    TMainMenu *MainMenu;
    TMenuItem *Om1;
    TMenuItem *Year1;
    TMenuItem *Rating1;
    TMenuItem *Artist1;
    TMenuItem *Situation1;
    TMenuItem *Mood1;
    TMenuItem *Genre1;
    TMenuItem *NewWave2;
    TMenuItem *N49;
    TMenuItem *Syntpop1;
    TPopupMenu *SongListPopupMenu;
    TMenuItem *Spelaupp1;
    TMenuItem *Spelauppislumpmssigordning1;
    TMenuItem *N61;
    TMenuItem *Egenskaper1;
    TButton *ShowAllButton;
    TLMDTrayIcon *TrayIcon;
    TMenuItem *Instllningar1;
    void __fastcall Hela1990talet1Click(TObject *Sender);
    void __fastcall Hela2000talet1Click(TObject *Sender);
    void __fastcall Hela1980talet1Click(TObject *Sender);
    void __fastcall Year1Click(TObject *Sender);
    void __fastcall Hela1970talet1Click(TObject *Sender);
    void __fastcall Hela1960talet1Click(TObject *Sender);
    void __fastcall Hela1950talet1Click(TObject *Sender);
    void __fastcall Rating1Click(TObject *Sender);
    void __fastcall Artist1Click(TObject *Sender);
    void __fastcall Situation1Click(TObject *Sender);
    void __fastcall Mood1Click(TObject *Sender);
    void __fastcall Genre1Click(TObject *Sender);
    void __fastcall GothicRock1Click(TObject *Sender);
    void __fastcall Punk2Click(TObject *Sender);
    void __fastcall Psykedeliskrock2Click(TObject *Sender);
    void __fastcall RockRoll1Click(TObject *Sender);
    void __fastcall Swing1Click(TObject *Sender);
    void __fastcall Humor2Click(TObject *Sender);
    void __fastcall SongListDblClick(TObject *Sender);
    void __fastcall SongListCompare(TObject *Sender, TListItem *Item1,
          TListItem *Item2, int Data, int &Compare);
    void __fastcall SongListColumnClick(TObject *Sender,
          TListColumn *Column);
    void __fastcall Spelauppislumpmssigordning1Click(TObject *Sender);
    void __fastcall ShowAllButtonClick(TObject *Sender);
    void __fastcall Egenskaper1Click(TObject *Sender);
    void __fastcall Om1Click(TObject *Sender);
    void __fastcall TrayIconClick(TObject *Sender);
    void __fastcall Arkiv1Click(TObject *Sender);
private:	// User declarations
    Mediator *MEDIATOR; /* TODO : Byt namn på facadobjekten till m_pXxxfacade */
    ImportExportFacade *IMPORTEXPORT;
    SongFacade *SONG;
    DatabaseEngine *DATABASE;
//    PlaylistFacade *PLAYLIST;
    PlayerFacade *PLAYER;

    Settings m_settings;
    int m_sortdirection;

    void UpdateSongList();
    void GetAndPutSongsInList(SongProperty *);
    AnsiString RemoveSingleAmpersands(const AnsiString &);
    void ShowWelcomeForm();
    bool CompareStrings(AnsiString, AnsiString);

    void ShowSongsFromYear(const AnsiString &);
    void ShowSongsWithRating(int); // 1-5
    void ShowSongsByArtist(const AnsiString &);
    void ShowSongsBySituation(const AnsiString &);
    void ShowSongsByMood(const AnsiString &);
    void ShowSongsInGenre(const AnsiString &);
public:		// User declarations
    __fastcall TMainForm(TComponent* Owner);
    __fastcall ~TMainForm();

    void __fastcall OnActivate(TObject *Sender);
};
//---------------------------------------------------------------------------
extern PACKAGE TMainForm *MainForm;
//---------------------------------------------------------------------------
#endif
